version: '2'
services: 
    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        environment: 
            KEYCLOAK_USER: admin 
            KEYCLOAK_PASSWORD: changeit
        ports:
            - 8080:8080
    
    steamidp:
        image: neothor/steam-openid-connect-provider
        build: ./src
        container_name: steamidp
        ports: 
            - 80:80            
        links:
            - keycloak